### ISSUE TITLE
Workload curation got failed with error "No module named tomli"

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/contrib#23]
Contrib Repo is able to build unsigned image of the workload, but it fails at signing the image.

I have met the perquisites for the curation app and also for the workload, but curation image creation is getting failed.

As part of Contrib Repo latest gsc is checked out, and gsc is updated to use tomli and tomli-w. 

Error:
```
Successfully tagged gsc-redis_x:latest-unsigned
Successfully built an unsigned graminized Docker image `gsc-redis_x:latest-unsigned` from original application image `redis_x:latest`.

Traceback (most recent call last):
  File "./gsc", line 10, in <module>
    from gsc import main # pylint: disable=import-error,wrong-import-position
  File "/home/intel/jenkins/workspace/anjali_curation_app_test/contrib_repo/Curated-Apps/gsc/./gsc.py", line 19, in <module>
    import tomli   # pylint: disable=import-error
ModuleNotFoundError: No module named 'tomli'
Untagged: gsc-redis_x:latest-unsigned
Deleted: sha256:07943e8f47bcf2fa1a11ea05822bffda7427c1fd030916c1b4589e4340b2f84f
Traceback (most recent call last):
  File "./gsc", line 10, in <module>
    from gsc import main # pylint: disable=import-error,wrong-import-position
  File "/home/intel/jenkins/workspace/anjali_curation_app_test/contrib_repo/Curated-Apps/gsc/./gsc.py", line 19, in <module>
    import tomli   # pylint: disable=import-error
ModuleNotFoundError: No module named 'tomli'
```

**Comment by dimakuv** [comment]
> As part of Contrib Repo latest gsc is checked out

Yeah, I guess we should always default (or hard-code, I don't remember if Curated Apps) to some specific GSC tag/commit, not just use `master`.

That said, I think the fix here is easy: just install `tomli` and `tomli-w` Python packages.

**Comment by anjalirai-intel** [comment]
This issue is fixed by moving GSC to tagged version where dependency is incorporated into templates
