### ISSUE TITLE
Docker run command from test page that spills over to new line does not work

### ISSUE THREAD

**Issue by jinengandhi-intel** [gramineproject/contrib#26]
For TF because of the insecure args the command at the test page is more than 1 line and hence when copying it from the test page to the terminal the EOL character is copied over, resulting in an incomplete command.

Example:

```
docker run --net=host --device=/dev/sgx/enclave:/dev/sgx_enclave -it gsc-tf-serving-base --model_name="resnet" --model_base_pat
h="/models/resnet"
```

 

Command in commands.txt does not have this issue.

**Comment by dimakuv** [comment]
@jinengandhi-intel This was not fixed yet?

**Comment by jinengandhi-intel** [comment]
Not yet, Anees plans to take this up now.
