### ISSUE TITLE
Pytorch with debug mode is failing with mbedtls_ssl_handshake with error -30592

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/contrib#32]
**Pytorch with debug mode is failing with mbedtls_ssl_handshake with error -30592**

**Workaround:** For debugging with attestation we need to set RA_TLS_ALLOW_DEBUG_ENCLAVE_INSECURE=1, this environment variable is not present as part of commands.txt. Pytorch requires attestation by-default, So when we run pytorch workload in debug mode, it ends up with handshake error.

If we set this environment variable for verifier image, pytorch workload works fine.

**Comment by dimakuv** [comment]
@jkr0103 Please look into this.

**Comment by jkr0103** [comment]
Please assign to me
