### ISSUE TITLE
Error running the tensorflow serving example 

### ISSUE THREAD

**Issue by shreejam21** [gramineproject/contrib#61]
Plz help with debugging 👍 

Here are the commands.txt after running the "gsc-tf-serving-base" created using the curated app. framework
I can successfully run a verifier imager
and then when run the command.txt command to run the gsc-tf-serving-base image -
It shows this error below : 

**ERROR : "/gramine/app_files/apploader.sh: line 24:     8 Killed                  gramine-sgx /gramine/app_files/entrypoint "${@}"**
![image](https://github.com/gramineproject/contrib/assets/115663197/6089dfcd-07df-49cf-a16f-be649c726468)

**Comment by dimakuv** [comment]
@aneessahib @jkr0103 Could you help with this issue? (These are the developers of the Curated Apps.)

**Comment by shreejam21** [comment]
@dimakuv thanks for responding. The Issue is fixed. I increased the size of my instance for 4core to 48!
