### ISSUE TITLE
All Intel-Confidential-Compute-for-X workloads failing with meson version v1.3.0

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/contrib#63]
Currently, All Confidential Compute workload is broken because of [https://github.com/gramineproject/gsc/issues/178](https://github.com/gramineproject/gsc/issues/178) because contrib uses gsc v1.5 and gramine v1.5

## Description
Recently meson version has been upgraded to v1.3.0, due to which gsc v1.5 build fails with error Cannot link_whole a custom or Rust target 'curl' into a static library 'sgx_util'.

Currently meson version has been restricted to meson>=0.56,!=1.2.*

**Comment by shiweiding** [comment]
Has the fix of GSC solved this issue? How can I find and fix GSC files in this project?

**Comment by shiweiding** [comment]
@anjalirai-intel Thanks for your reply and modifications. How can I update this patch to the "contrib" repo. I installed the Gramine by using the deb package, so I'm confused about where I should add it. I changed the control file in the debian folder of the contrib project to restrict the version of meson but seems not to work.

**Comment by anjalirai-intel** [comment]
As temporarily you can do this, because we will soon have release for gramineproject which should fix this issue

gsc patch file should be placed in `Intel-Confidential-Compute-for-X` and make below change in contrib

```
diff --git a/Intel-Confidential-Compute-for-X/util/curation_script.sh b/Intel-Confidential-Compute-for-X/util/curation_script.sh
index 0ab5212..d7984b1 100755
--- a/Intel-Confidential-Compute-for-X/util/curation_script.sh
+++ b/Intel-Confidential-Compute-for-X/util/curation_script.sh
@@ -126,6 +126,7 @@ create_gsc_image () {
     rm -rf gsc >/dev/null 2>&1
     git clone --depth 1 --branch v1.5 https://github.com/gramineproject/gsc.git
     cd gsc
+    git apply ../gsc_fix.patch
     cp -f config.yaml.template config.yaml
     sed -i 's|ubuntu:.*|'$distro'"|' config.yaml
```
